name: Build and Push Docker Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for the Docker image'
        required: true
        default: 'latest'
      model:
        description: 'Model to build and push (schnell, dev, fill-dev, canny-dev, depth-dev, redux-dev, redux-schnell, schnell-lora, dev-lora, hotswap-lora)'
        required: true
        default: 'dev'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codew
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Select model
      run: |
        echo "Model selected: ${{ github.event.inputs.model }}"
        ./script/select.sh ${{ github.event.inputs.model }}
        
    - name: Install Cog
      run: |
        sudo curl -o /usr/local/bin/cog -L "https://github.com/replicate/cog/releases/latest/download/cog_$(uname -s)_$(uname -m)"
        sudo chmod +x /usr/local/bin/cog
        
    - name: Build Docker image with Cog
      run: cog build -t ghcr.io/${{ github.repository }}/pb-cog:${{ github.event.inputs.version }}

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/${{ github.repository }}/pb-cog:${{ github.event.inputs.version }}